[workspace]
members = [
    "bellman",
    "librustzcash",
    "pairing",
    "sapling-crypto",
    "zcash_primitives",
    "zcash_proofs",
    "zcash_wallet",
    "zip32",
]

[profile.release]
lto = false
panic = 'abort'
codegen-units = 1
